---
- hosts: web_servers
  become: true
  tasks:
    - name: install dependency
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add repository docker to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Creates directory
      file:
        path: /var/local/lux
        state: directory
    - copy:
        src: ./Dockerfile
        dest: /var/local/lux/Dockerfile
    - name: start docker and enable  autostart
      service:
        name: docker
        state: started
        enabled: yes
    - name: Add the user 'ubuntu'in group of 'docker'
      #ansible.builtin.user:
      user:
        name: ubuntu
        group: docker
        append: yes
      become: yes
